[01-Dec-2024 14:23:36 CET] [2024-12-01T14:23:36.448029+01:00] request.INFO: Matched route "contao_managerapi_task__invoke". {"route":"contao_managerapi_task__invoke","route_parameters":{"_route":"contao_managerapi_task__invoke","_controller":"_ContaoManager\\Contao\\ManagerApi\\Controller\\TaskController"},"request_uri":"https://duc-contao-5.local/contao-manager.phar.php/api/task","method":"PUT"} []
[01-Dec-2024 14:23:36 CET] [2024-12-01T14:23:36.480772+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":4} []
[01-Dec-2024 14:23:36 CET] [2024-12-01T14:23:36.486651+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\LoginAuthenticator"} []
[01-Dec-2024 14:23:36 CET] [2024-12-01T14:23:36.487589+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\LoginAuthenticator"} []
[01-Dec-2024 14:23:36 CET] [2024-12-01T14:23:36.489960+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\PasswordlessAuthenticator"} []
[01-Dec-2024 14:23:36 CET] [2024-12-01T14:23:36.490518+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\PasswordlessAuthenticator"} []
[01-Dec-2024 14:23:36 CET] [2024-12-01T14:23:36.490523+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[01-Dec-2024 14:23:36 CET] [2024-12-01T14:23:36.493562+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\TokenAuthenticator"} []
[01-Dec-2024 14:23:36 CET] [2024-12-01T14:23:36.493578+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\TokenAuthenticator"} []
[01-Dec-2024 14:23:36 CET] [2024-12-01T14:23:36.493593+01:00] security.DEBUG: Calling getCredentials() on guard authenticator. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[01-Dec-2024 14:23:36 CET] [2024-12-01T14:23:36.497261+01:00] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[01-Dec-2024 14:23:36 CET] [2024-12-01T14:23:36.513114+01:00] security.INFO: Guard authentication successful! {"token":{"_ContaoManager\\Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken":"PostAuthenticationGuardToken(user=\"duc\", authenticated=true, roles=\"ROLE_ADMIN\")"},"authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[01-Dec-2024 14:23:37 CET] [2024-12-01T14:23:36.514322+01:00] security.DEBUG: Guard authenticator set no success response: request continues. {"authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[01-Dec-2024 14:23:37 CET] [2024-12-01T14:23:36.514328+01:00] security.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[01-Dec-2024 14:23:37 CET] [2024-12-01T14:23:36.750649+01:00] app.ERROR: Uncaught PHP Exception _ContaoManager\Symfony\Component\HttpKernel\Exception\BadRequestHttpException: "A task is already active" at phar:///shared/httpd/duc-contao-5/public/contao-manager.phar.php/api/Controller/TaskController.php line 56 {"exception":"[object] (_ContaoManager\\Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException(code: 0): A task is already active at phar:///shared/httpd/duc-contao-5/public/contao-manager.phar.php/api/Controller/TaskController.php:56)"} []
