[28-Nov-2024 17:34:07 CET] [2024-11-28T17:34:07.562566+01:00] request.INFO: Matched route "contao_managerapi_contao_maintenancemode__invoke". {"route":"contao_managerapi_contao_maintenancemode__invoke","route_parameters":{"_route":"contao_managerapi_contao_maintenancemode__invoke","_controller":"_ContaoManager\\Contao\\ManagerApi\\Controller\\Contao\\MaintenanceModeController"},"request_uri":"https://duc-contao-5.local/contao-manager.phar.php/api/contao/maintenance-mode","method":"GET"} []
[28-Nov-2024 17:34:07 CET] [2024-11-28T17:34:07.779642+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":4} []
[28-Nov-2024 17:34:07 CET] [2024-11-28T17:34:07.801551+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\LoginAuthenticator"} []
[28-Nov-2024 17:34:07 CET] [2024-11-28T17:34:07.804457+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\LoginAuthenticator"} []
[28-Nov-2024 17:34:07 CET] [2024-11-28T17:34:07.809329+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\PasswordlessAuthenticator"} []
[28-Nov-2024 17:34:07 CET] [2024-11-28T17:34:07.811109+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\PasswordlessAuthenticator"} []
[28-Nov-2024 17:34:07 CET] [2024-11-28T17:34:07.811122+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[28-Nov-2024 17:34:07 CET] [2024-11-28T17:34:07.819902+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[28-Nov-2024 17:34:07 CET] [2024-11-28T17:34:07.823913+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\TokenAuthenticator"} []
[28-Nov-2024 17:34:07 CET] [2024-11-28T17:34:07.823945+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\TokenAuthenticator"} []
[28-Nov-2024 17:34:07 CET] [2024-11-28T17:34:07.849487+01:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[28-Nov-2024 17:34:07 CET] [2024-11-28T17:34:07.866528+01:00] app.ERROR: Uncaught PHP Exception _ContaoManager\Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at phar:///shared/httpd/duc-contao-5/public/contao-manager.phar.php/api/EventListener/ExceptionListener.php line 88 {"exception":"[object] (_ContaoManager\\Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at phar:///shared/httpd/duc-contao-5/public/contao-manager.phar.php/api/EventListener/ExceptionListener.php:88)\n[previous exception] [object] (_ContaoManager\\Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at phar:///shared/httpd/duc-contao-5/public/contao-manager.phar.php/vendor/symfony/security-http/Firewall/AccessListener.php:113)"} []
[28-Nov-2024 19:45:27 CET] [2024-11-28T19:45:23.930670+01:00] request.INFO: Matched route "contao_managerapi_task__invoke". {"route":"contao_managerapi_task__invoke","route_parameters":{"_route":"contao_managerapi_task__invoke","_controller":"_ContaoManager\\Contao\\ManagerApi\\Controller\\TaskController"},"request_uri":"https://duc-contao-5.local/contao-manager.phar.php/api/task","method":"GET"} []
[28-Nov-2024 19:45:27 CET] [2024-11-28T19:45:25.732168+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":4} []
[28-Nov-2024 19:45:27 CET] [2024-11-28T19:45:25.967073+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\LoginAuthenticator"} []
[28-Nov-2024 19:45:27 CET] [2024-11-28T19:45:25.998970+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\LoginAuthenticator"} []
[28-Nov-2024 19:45:27 CET] [2024-11-28T19:45:26.039206+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\PasswordlessAuthenticator"} []
[28-Nov-2024 19:45:27 CET] [2024-11-28T19:45:26.052257+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\PasswordlessAuthenticator"} []
[28-Nov-2024 19:45:27 CET] [2024-11-28T19:45:26.052356+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[28-Nov-2024 19:45:27 CET] [2024-11-28T19:45:26.165234+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[28-Nov-2024 19:45:27 CET] [2024-11-28T19:45:26.237766+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\TokenAuthenticator"} []
[28-Nov-2024 19:45:28 CET] [2024-11-28T19:45:26.240070+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\TokenAuthenticator"} []
[28-Nov-2024 19:45:28 CET] [2024-11-28T19:45:26.815658+01:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[28-Nov-2024 19:45:28 CET] [2024-11-28T19:45:27.366177+01:00] app.ERROR: Uncaught PHP Exception _ContaoManager\Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at phar:///shared/httpd/duc-contao-5/public/contao-manager.phar.php/api/EventListener/ExceptionListener.php line 88 {"exception":"[object] (_ContaoManager\\Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at phar:///shared/httpd/duc-contao-5/public/contao-manager.phar.php/api/EventListener/ExceptionListener.php:88)\n[previous exception] [object] (_ContaoManager\\Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at phar:///shared/httpd/duc-contao-5/public/contao-manager.phar.php/vendor/symfony/security-http/Firewall/AccessListener.php:113)"} []
